// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUsS06zs8Ou3EHU50pCxzQxUgGEKqSl8c',
    appId: '1:673091504645:web:803b0138f79d204cfb6a6c',
    messagingSenderId: '673091504645',
    projectId: 'mad-project-37092',
    authDomain: 'mad-project-37092.firebaseapp.com',
    storageBucket: 'mad-project-37092.firebasestorage.app',
    measurementId: 'G-NB7XSYX8BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2EkmzmOLPptkgbx63BxhjKLX9pLxj9mY',
    appId: '1:673091504645:android:edafe1f0b0044543fb6a6c',
    messagingSenderId: '673091504645',
    projectId: 'mad-project-37092',
    storageBucket: 'mad-project-37092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvOS9OgXEtv6asEpPmFMHSl6owcOjodcc',
    appId: '1:673091504645:ios:d4436989c05d46b6fb6a6c',
    messagingSenderId: '673091504645',
    projectId: 'mad-project-37092',
    storageBucket: 'mad-project-37092.firebasestorage.app',
    iosBundleId: 'com.example.shifteasePune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvOS9OgXEtv6asEpPmFMHSl6owcOjodcc',
    appId: '1:673091504645:ios:d4436989c05d46b6fb6a6c',
    messagingSenderId: '673091504645',
    projectId: 'mad-project-37092',
    storageBucket: 'mad-project-37092.firebasestorage.app',
    iosBundleId: 'com.example.shifteasePune',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUsS06zs8Ou3EHU50pCxzQxUgGEKqSl8c',
    appId: '1:673091504645:web:14030f5983a59f07fb6a6c',
    messagingSenderId: '673091504645',
    projectId: 'mad-project-37092',
    authDomain: 'mad-project-37092.firebaseapp.com',
    storageBucket: 'mad-project-37092.firebasestorage.app',
    measurementId: 'G-DS9NZL2CYN',
  );
}
